# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

vars:
  RUNNER: uv run

tasks:
  default:
    desc: Show available commands
    cmd: task --list

  # ----------------------------------------------------------------------------
  # Database Commands (Namespace: db)
  # ----------------------------------------------------------------------------

  revision:
    desc: |
      Create new Alembic migration (Usage: task db:revision -- "your message here")
    cmds:
      - '{{.RUNNER}} alembic revision -m "{{.CLI_ARGS}}"'

  current:
    desc: Run alembic current (check migration status)
    cmd: "{{.RUNNER}} alembic current"

  history:
    desc: Show alembic migration history
    cmd: "{{.RUNNER}} alembic history"

  upgrade:
    desc: Run alembic upgrade head
    cmd: "{{.RUNNER}} alembic upgrade head"

  downgrade:
    desc: Downgrade database by one revision
    cmd: "{{.RUNNER}} alembic downgrade -1"
