"""Protocol interface — structural typing, no inheritance coupling."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from yamactl.core.models import (
    NetRadioListInfo,
    NetRadioStatus,
    PowerState,
    ReceiverStatus,
    TunerStatus,
)


@runtime_checkable
class ReceiverProtocol(Protocol):
    def __enter__(self) -> ReceiverProtocol: ...
    def __exit__(self, *args: object) -> None: ...
    def get_status(self) -> ReceiverStatus: ...
    def set_power(self, state: PowerState) -> None: ...
    def get_mute(self) -> bool: ...
    def set_mute(self, enabled: bool) -> None: ...
    def get_volume_db(self) -> float: ...
    def set_volume_db(self, value: float) -> None: ...
    def volume_up(self, steps: int = 1) -> None: ...
    def volume_down(self, steps: int = 1) -> None: ...
    def set_input(self, source: str) -> None: ...
    def list_inputs(self) -> list[str]: ...
    def load_scene(self, scene: int) -> None: ...
    def set_dsp_mode(self, mode: str) -> None: ...
    def set_straight(self, enabled: bool) -> None: ...
    def set_direct(self, enabled: bool) -> None: ...
    def set_sleep(self, minutes: int | None) -> None: ...
    def send_raw_ynca(self, command: str) -> str: ...
    def send_raw_xml(self, xml: str) -> str: ...
    def get_tuner_status(self) -> TunerStatus: ...
    def set_tuner_band(self, band: str) -> None: ...
    def set_tuner_fm_freq(self, mhz: float) -> None: ...
    def set_tuner_am_freq(self, khz: int) -> None: ...
    def set_tuner_preset(self, preset_num: int) -> None: ...
    def get_netradio_status(self) -> NetRadioStatus: ...
    def set_netradio_playback(self, action: str) -> None: ...
    def set_netradio_preset(self, preset_num: int) -> None: ...
    def get_netradio_list(self) -> NetRadioListInfo: ...
    def netradio_select(self, line: int) -> None: ...
    def netradio_back(self) -> None: ...
    def netradio_cursor(self, direction: str) -> None: ...
    def play_netradio_url(self, url: str, title: str) -> None: ...
    def pause_netradio_url(self) -> None: ...
    def stop_netradio_url(self) -> None: ...
    def get_server_status(self) -> NetRadioStatus: ...
